### PR TITLE
admin: added admin node as a salt minion 

### PR DESCRIPTION
**Pull request by mssola**
See kubic-project/salt#111
Depends on #68

### CODE REVIEW

**Comment by mjura** [comment]
Please rebase this change

**Comment by mssola** [comment]
@mjura I'll rebase as soon as #68 does it as well.

**Comment by mssola** [comment]
@mjura rebased!

**Comment by mjura** [comment]
Has to be rebased

**Comment by mssola** [comment]
I'll rebase whenever #68 gets merged (I don't want to be rebasing multiple times...)

**Comment by mssola** [comment]
Just rebased, but I'll have to test it again...

**Comment by kiall** [comment]
This project is no longer maintained, closing the open PRs...

**Pull request closed without merging**
