### PR TITLE
Keep in sync with the manifests from caasp-manifests

### PR DESCRIPTION
**Pull request by inercia**
Script for downloading the manifests files from the repos we use for production, replacing some read-only directories by the read-write one we use for uploading with Terraform.

### CODE REVIEW

**Comment by inercia** [comment]
> Since these files are going to be downloaded and probably they will change depending on what context they run on, it may make sense to remove them from git and add them to the .gitignore file.

These manifest files are far from being _generated files_ and we should keep them in the repo and not exclude them with `.gitignore`. Otherwise we will make things (even) harder for someone that wants to use this repo.

Maybe it has not being clearly stated but this script is _not for users but for us_. We will run it from time to time in order to keep in sync both repos. I'm not interested in customizing it with flavours or whatever, I just want to have the manifests we have been having but in sync with the _caasp-manifest_ repo.

**Comment by ereslibre** [comment]
The problem is that by default this project can be cloned by other people, and they might not have access to a sle docker image, so our defaults should be external contributors friendly.

Maybe it's time to remove the dashboard from terraform completely (so we would maintaining less combinations).

**Comment by inercia** [comment]
> The problem is that by default this project can be cloned by other people, and they might not have access to a sle docker image, so our defaults should be external contributors friendly.

> Maybe it's time to remove the dashboard from terraform completely (so we would maintaining less combinations).

Rafa, this repo is used _only by us_. It has only 13 starts! It is used for testing by a bunch of people, so we don't need to be generic or portable or anything like that, it must just serve our purpose: to test CaaSP with sle and maybe for doing some demos. We can do what you proposed when we have the first _"hey guys, this is not portable enough"_ issue... and it cannot be filed by you from a fake github account. ;)

**Comment by flavio** [comment]
I'm not happy about the current fragmentation of the manifest files, we have to think more about how to solve that after the hackweek. Please wait before merging the PR, I would like to talk with all of you about the issue.

**Pull request closed without merging**
