### PR TITLE
Fix kubelet arguments for version >= 1.6.1

### PR DESCRIPTION
**Pull request by mjura**

### CODE REVIEW

**Comment by mjura** [comment]
@ereslibre : It works, fine problem is somewhere else https://github.com/kubic-project/terraform/blob/master/provision/dashboard/manifests/salt.yaml#L24. On openSUSE we are trying to use images based on sle12sp2 which we are not providing for it.

**Comment by robdaemon** [comment]
@mjura I'm about to open a PR for the latter to revert to the original behavior. The repo is broken and you cannot do an install right now :(

**Comment by PI-Victor** [comment]
@robdaemon what exactly is broken for you, i remember running this just fine on Fri?

**Comment by robdaemon** [comment]
@PI-Victor If you clone this repo, and run `./contrib/libvirt/k8s-libvirt.sh apply`, the cluster will fail to start. It references images that do not exist in Docker Hub.

**Comment by robdaemon** [comment]
See kubic-project/terraform#36 and kubic-project/salt#38 to restore local deployment functionality.

**Pull request merged**
