### PR TITLE
Use cloud-init user_data for setting some things

### PR DESCRIPTION
**Pull request by inercia**
Use the cloud-init `user_data` for setting some things...

Requires this PR dmacvicar/terraform-provider-libvirt#104 from `terraform-libvirt-provider`

### CODE REVIEW

**Comment by mjura** [comment]
:+1: it looks ok

**Comment by inercia** [comment]
Blocked until dmacvicar/terraform-provider-libvirt#104 is merged

**Comment by inercia** [comment]
dmacvicar/terraform-provider-libvirt#104 has been merged, but we will hold on until the new package is released

**Comment by flavio** [comment]
The new package has been released on OBS

**Comment by PI-Victor** [comment]
speaking of which, can this be merged? @inercia can you retrigger the tests? they've failed in the past.

**Comment by inercia** [comment]
I think this code is not useful anymore: we should start from scratch and see how to integrate cloud-init in our Terraform code.

**Pull request closed without merging**
