### PR TITLE
Set TF parallelism to 1

### PR DESCRIPTION
**Pull request by kiall**
Attempting to reduce CI failures

### CODE REVIEW

**Comment by kiall** [comment]
Using admin powers to merge... CI doesn't actually seem to test this repo correctly anyway :(

**Comment by aocole** [comment]
@kiall did this change accomplish anything for CI? It slows down development cycle...

**Comment by kiall** [comment]
@aocole yea, it did - most (all?) of the terraform hangs are now gone, making things much more reliable. Maybe we should make it configurable now?

**Comment by ereslibre** [comment]
Parallelism changes is saving hours of work for me... no hangs at all since it was introduced (at least for me).

**Pull request merged**
