### PR TITLE
Fixing ability to start via Terraform locally

### PR DESCRIPTION
**Pull request by robdaemon**
This reverts a commit that was referencing Docker images that do not exist on Docker Hub.

This restores the ability to start a cluster locally via `./contrib/libvirt/k8s-libvirt.sh apply`

### CODE REVIEW

**Comment by robdaemon** [comment]
I think the e2e test failed because it ran two at the same time, but I'm not sure.

**Comment by ereslibre** [comment]
This was already proposed on https://github.com/kubic-project/terraform/pull/30.

I agree with the change, but we need to find a better way to support both opensuse and sle based images or remove the dashboard creation functionality completely from terraform (so terraform would only allow to spawn workers, never a dashboard, since we can already do that with the development environment). I think we need to discuss this, since it would reduce the scenarios we need to maintain too. 

If you apply the cluster with FLAVOUR=caasp (using the contrib script) I think it should work. What is broken is the opensuse case.

**Comment by robdaemon** [comment]
Okay, this PR is failing because it needs the *other* PR I opened :)

**Comment by robdaemon** [comment]
@ereslibre Okay, I'll give that a shot. Maybe the default flavor needs to be caasp and not opensuse then? This has had me stuck for a week at this point :( The CaaS image it downloads in that flavor is really large, and can only be downloaded over the VPN. That's a real problem for those of us in North America :(

**Comment by PI-Victor** [comment]
@robdaemon that is a huge downside i agree.
as a workaround you can use @ereslibre [script](https://github.com/ereslibre/build-caasp-iso) that builds a local iso from OBS and copy it to the `terraform` directory and and then set `LATEST_IMAGE=false` when terraforming. 
The script is slow the first time, till it checks out all the libs, but works increasingly faster afterwards.
just as an idea, not sure how great that would work out for you. probably a bit better than pulling images all the time.
or you could just use `LATEST_IMAGE=false` and only pull the latest ISO a few times per day.

**Comment by robdaemon** [comment]
So, setting the flavor doesn't work either. I still references non-existent images:

```
" level=error msg="Handler for GET /v1.24/images/sles12/velum:0.0/json returned error: No such image: sles12/velum:0.0"
" level=error msg="Handler for GET /v1.24/images/sles12/velum:0.0/json returned error: No such image: sles12/velum:0.0"
" level=error msg="Handler for GET /v1.24/images/sles12/mariadb:10.0/json returned error: No such image: sles12/mariadb:10.0"
" level=error msg="Handler for GET /v1.24/images/sles12/salt-master:2015.8.12/json returned error: No such image: sles12/salt-master:2015.8.12"
" level=error msg="Handler for GET /v1.24/images/sles12/salt-api:2015.8.12/json returned error: No such image: sles12/salt-api:2015.8.12"
" level=error msg="Handler for GET /v1.24/images/sles12/salt-minion:2015.8.12/json returned error: No such image: sles12/salt-minion:2015.8.12"
" level=error msg="Handler for GET /v1.24/images/sles12/velum:0.0/json returned error: No such image: sles12/velum:0.0"
" level=error msg="Handler for GET /v1.24/images/sles12/velum:0.0/json returned error: No such image: sles12/velum:0.0"
" level=error msg="Handler for GET /v1.24/images/sles12/mariadb:10.0/json returned error: No such image: sles12/mariadb:10.0"
" level=error msg="Handler for GET /v1.24/images/sles12/salt-master:2015.8.12/json returned error: No such image: sles12/salt-master:2015.8.12"
" level=error msg="Handler for GET /v1.24/images/sles12/salt-api:2015.8.12/json returned error: No such image: sles12/salt-api:2015.8.12"
" level=error msg="Handler for GET /v1.24/images/sles12/salt-minion:2015.8.12/json returned error: No such image: sles12/salt-minion:2015.8.12"
" level=error msg="Handler for GET /v1.24/images/sles12/velum:0.0/json returned error: No such image: sles12/velum:0.0"
" level=error msg="Attempting next endpoint for pull after error: unauthorized: authentication required"
" level=error msg="Not continuing with pull after error: Error: image sles12/velum:0.0 not found"
" level=error msg="Handler for GET /v1.24/images/sles12/mariadb:10.0/json returned error: No such image: sles12/mariadb:10.0"
" level=error msg="Attempting next endpoint for pull after error: unauthorized: authentication required"
" level=error msg="Not continuing with pull after error: Error: image sles12/mariadb:10.0 not found"
" level=error msg="Handler for GET /v1.24/images/sles12/velum:0.0/json returned error: No such image: sles12/velum:0.0"
" level=error msg="Handler for GET /v1.24/images/sles12/salt-master:2015.8.12/json returned error: No such image: sles12/salt-master:2015.8.12"
" level=error msg="Attempting next endpoint for pull after error: unauthorized: authentication required"
" level=error msg="Not continuing with pull after error: Error: image sles12/salt-master:2015.8.12 not found"
" level=error msg="Handler for GET /v1.24/images/sles12/salt-api:2015.8.12/json returned error: No such image: sles12/salt-api:2015.8.12"
" level=error msg="Attempting next endpoint for pull after error: unauthorized: authentication required"
" level=error msg="Not continuing with pull after error: Error: image sles12/salt-api:2015.8.12 not found"
" level=error msg="Handler for GET /v1.24/images/sles12/salt-minion:2015.8.12/json returned error: No such image: sles12/salt-minion:2015.8.12"
" level=error msg="Attempting next endpoint for pull after error: unauthorized: authentication required"
" level=error msg="Not continuing with pull after error: Error: image sles12/salt-minion:2015.8.12 not found"
```

I can see that there are zypper packages installed:

```
dashboard:~ # sudo zypper info sles12-salt-minion-2015.8.12-docker-image
Loading repository data...
Reading installed packages...


Information for package sles12-salt-minion-2015.8.12-docker-image:
------------------------------------------------------------------
Repository     : @System                                                     
Name           : sles12-salt-minion-2015.8.12-docker-image                   
Version        : 1.0.0-20170413                                              
Arch           : x86_64                                                      
Vendor         : SUSE LLC <https://www.suse.com/>                            
Installed Size : 67.4 MiB                                                    
Installed      : Yes                                                         
Status         : up-to-date                                                  
Source package : sles12-salt-minion-2015.8.12-docker-image-1.0.0-20170413.src
Summary        : Package with sles12-salt-minion 2015.8.12 docker image      
Description    :                                                             
    This package contains the official sles12-salt-minion 2015.8.12
    image for Docker.
```

but Docker can't seem to use them.

**Comment by ereslibre** [comment]
This is because no `container-feeder` is executed on the KVM images (or it is failing), so these images are not imported.

**Comment by inercia** [comment]
I think this PR is outdated. The manifest where updated automatically in #34 and the `container-feeder` will be started as part of the provisioning in #37.

**Pull request closed without merging**
